default:
  description: 'Default task for grunt. Spits out some info about your JS then kicks off a watch.'
  tasks:
    - 'clean'
    - 'audit'
    - 'watch:default'

############################
# Shortcuts
############################
jsb:
  description: 'Alias for beautifying files.'
  tasks:
    - 'eslint:fix'

lint:
  description: 'Make sure the JS checks out.'
  tasks:
    - 'eslint:lint'

############################
# Tasks for Focusing on a particular task
############################
o-lint:
  description: 'Watch files and run tasks specific to linting.'
  tasks:
    - 'clean'
    - 'watch:_lint_optimized'

o-docs:
  description: 'Watch files and run tasks specific to writing documentation.'
  tasks:
    - 'clean'
    - 'jsdoc:dev'
    - 'watch:_docs_optimized'

############################
# Helper tasks
############################

audit:
- 'todo'
- 'jsinspect'

############################
# Internal tasks
############################
#---------------------------
# Watch Helpers
#---------------------------

# if you rename this task, you need to update the string in grunt/config/watch.js
_js_on_watch:
  - 'jsb'
  - 'jsdoc:dev'

# if you rename this task, you need to update the string in grunt/config/watch.js
_js_o_lint_on_watch:
  - 'jsb'

# if you rename this task, you need to update the string in grunt/config/watch.js
_js_o_docs_on_watch:
  - 'jsdoc:dev'
  - 'jsb'
